name: MooContentAssist
author: NKjoep
category: Forms
tags: [editor, content, assist, completer]
docs: http://moocontentassist.altervista.org/docs/
demo: http://moocontentassist.altervista.org/
current: 0.80.3
